version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-function-delay"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9be2mmqosbho"
s3_prefix = "step-function-delay"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
